function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "lamp_stateFlow"};
	this.sidHashMap["lamp_stateFlow"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "lamp_stateFlow:1"};
	this.sidHashMap["lamp_stateFlow:1"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Chart"] = {sid: "lamp_stateFlow:1"};
	this.sidHashMap["lamp_stateFlow:1"] = {rtwname: "<Root>/Chart"};
	this.rtwnameHashMap["<Root>/Lamp"] = {sid: "lamp_stateFlow:2"};
	this.sidHashMap["lamp_stateFlow:2"] = {rtwname: "<Root>/Lamp"};
	this.rtwnameHashMap["<Root>/Lamp1"] = {sid: "lamp_stateFlow:3"};
	this.sidHashMap["lamp_stateFlow:3"] = {rtwname: "<Root>/Lamp1"};
	this.rtwnameHashMap["<Root>/Lamp2"] = {sid: "lamp_stateFlow:4"};
	this.sidHashMap["lamp_stateFlow:4"] = {rtwname: "<Root>/Lamp2"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "lamp_stateFlow:10"};
	this.sidHashMap["lamp_stateFlow:10"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<Root>/Out2"] = {sid: "lamp_stateFlow:11"};
	this.sidHashMap["lamp_stateFlow:11"] = {rtwname: "<Root>/Out2"};
	this.rtwnameHashMap["<Root>/Out3"] = {sid: "lamp_stateFlow:12"};
	this.sidHashMap["lamp_stateFlow:12"] = {rtwname: "<Root>/Out3"};
	this.rtwnameHashMap["<S1>:4"] = {sid: "lamp_stateFlow:1:4"};
	this.sidHashMap["lamp_stateFlow:1:4"] = {rtwname: "<S1>:4"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "lamp_stateFlow:1:1"};
	this.sidHashMap["lamp_stateFlow:1:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S1>:3"] = {sid: "lamp_stateFlow:1:3"};
	this.sidHashMap["lamp_stateFlow:1:3"] = {rtwname: "<S1>:3"};
	this.rtwnameHashMap["<S1>:2"] = {sid: "lamp_stateFlow:1:2"};
	this.sidHashMap["lamp_stateFlow:1:2"] = {rtwname: "<S1>:2"};
	this.rtwnameHashMap["<S1>:5"] = {sid: "lamp_stateFlow:1:5"};
	this.sidHashMap["lamp_stateFlow:1:5"] = {rtwname: "<S1>:5"};
	this.rtwnameHashMap["<S1>:7"] = {sid: "lamp_stateFlow:1:7"};
	this.sidHashMap["lamp_stateFlow:1:7"] = {rtwname: "<S1>:7"};
	this.rtwnameHashMap["<S1>:6"] = {sid: "lamp_stateFlow:1:6"};
	this.sidHashMap["lamp_stateFlow:1:6"] = {rtwname: "<S1>:6"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
